//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _CERBERUS_HARDWARE_H_
#define _CERBERUS_HARDWARE_H_

#include <TinyCLR_Interop.h>
struct Library_Cerberus_Hardware_Cerberus_Hardware_QuadratureEncoder
{
    static const int FIELD___dispatcher = 1;
    static const int FIELD___inputCapture = 2;
    static const int FIELD__<Count>k__BackingField = 3;
    static const int FIELD__<InputCaptureEnabled>k__BackingField = 4;
    static const int FIELD__<CountEnabled>k__BackingField = 5;

    TINYCLR_NATIVE_DECLARE(get_Count___I4);
    TINYCLR_NATIVE_DECLARE(set_Count___VOID__I4);
    TINYCLR_NATIVE_DECLARE(get_InputCaptureEnabled___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(set_InputCaptureEnabled___VOID__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(get_CountEnabled___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(set_CountEnabled___VOID__BOOLEAN);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Cerberus_Hardware;

#endif  //_CERBERUS_HARDWARE_H_
