//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Cerberus_Hardware.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Cerberus_Hardware_Cerberus_Hardware_QuadratureEncoder::get_Count___I4,
    Library_Cerberus_Hardware_Cerberus_Hardware_QuadratureEncoder::set_Count___VOID__I4,
    Library_Cerberus_Hardware_Cerberus_Hardware_QuadratureEncoder::get_InputCaptureEnabled___BOOLEAN,
    Library_Cerberus_Hardware_Cerberus_Hardware_QuadratureEncoder::set_InputCaptureEnabled___VOID__BOOLEAN,
    Library_Cerberus_Hardware_Cerberus_Hardware_QuadratureEncoder::get_CountEnabled___BOOLEAN,
    Library_Cerberus_Hardware_Cerberus_Hardware_QuadratureEncoder::set_CountEnabled___VOID__BOOLEAN,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Cerberus_Hardware =
{
    "Cerberus_Hardware", 
    0xD42C42B1,
    method_lookup
};

